# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Yogit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Yogit

  target 'YogitTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'YogitUITests' do
    # Pods for testing
  end

  pod 'Alamofire', '~> 5.5'
  pod 'SnapKit', '~> 5.6.0'
  pod 'IQKeyboardManagerSwift', '~> 6.5.0'
  pod "BSImagePicker", "~> 3.1" 
  pod 'Kingfisher', '~> 7.0'
  pod 'BulletinBoard'
end
